/*
* @description	Unit test class. Handles all tests for Account.trigger & AccountTriggerHandler.cls
* @author		Davin Casey
* @deprecated	False
*/
@isTest
private class AccountTriggerHandlerTest {

	/*
	* @description	Here is where you write your own unit tests, sorry :)
	* @author		Davin Casey
	* @return
	* @param
	* @throws
	* @deprecated	False
	*/
	@isTest
	private static void testOne () {}

	/*
	* @description	Here is where you create your test data.
	* @author		Davin Casey
	* @return
	* @param
	* @throws
	* @deprecated	False
	*/
	@testSetup
	private static void setupData () {}
}
